// src/App.tsx
import { Suspense, lazy, useMemo, useState } from 'react'
import './App.css'

const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))

function App() {
  const [version, setVersion] = useState(0)

  const Profile = useMemo(
    () => lazy(() => wait(1200).then(() => import('./Profile'))),
    [version]
  )

  return (
    <div className="app">
      <h1>Suspense demo</h1>
      <p>Lazy-loaded profile waits 1.2s so you can see the fallback.</p>

      <button onClick={() => setVersion((v) => v + 1)}>Reload profile</button>

      <Suspense
        key={version}
        fallback={<p className="loader">Loading profile...</p>}
      >
        <Profile />
      </Suspense>
    </div>
  )
}

export default App

// src/app.component.ts
import { Component, Type } from '@angular/core';
import { CommonModule, NgComponentOutlet } from '@angular/common';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, NgComponentOutlet],
  templateUrl: './app.component.html',
  styleUrls: ['./App.css']
})
export class AppComponent {
  version = 0;
  ProfileComponent: Type<any> | null = null;
  loading = false;

  constructor() {
    this.loadProfile();
  }

  reloadProfile() {
    this.version++;
    this.ProfileComponent = null;
    this.loadProfile();
  }

  private async loadProfile() {
    this.loading = true;
    await this.wait(1200);
    const module = await import('./profile.component');
    this.ProfileComponent = module.ProfileComponent;
    this.loading = false;
  }

  private wait(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}

<div class="app">
  <h1>Suspense demo</h1>
  <p>Lazy-loaded profile waits 1.2s so you can see the fallback.</p>

  <button (click)="reloadProfile()">Reload profile</button>

  @if (loading) {
    <p class="loader">Loading profile...</p>
  } @else if (ProfileComponent) {
    <ng-container *ngComponentOutlet="ProfileComponent" />
  }
</div>
